version: 2
registries:
  composer-repository-repo-packagist-com-personare:
    type: composer-repository
    url: https://repo.packagist.com/personare
    username: elvishp2006
    password: "${{secrets.COMPOSER_REPOSITORY_REPO_PACKAGIST_COM_PERSONARE_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: slevomat/coding-standard
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
  registries:
  - composer-repository-repo-packagist-com-personare
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.2.3
  - dependency-name: "@wordpress/eslint-plugin"
    versions:
    - 8.0.1
    - 9.0.0
    - 9.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
